jobs:
  include:
  - stage: test
    language: node.js
    nodejs:
    - '10.11'
    before_install:
    - npm install -g swagger-cli
    before_script:
    - cd api/
    script:
    - swagger-cli validate api.yaml
    cache:
      directories:
      - node_modules

  - stage: test
    language: go
    go:
    - '1.11'
    env:
    - GO111MODULE=on
    script: go test
    cache:
      directories:
      - $HOME/.cache/go-build
      - $GOPATH/pkg/mod

  - stage: test
    env:
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor
    language: go
    go:
    - '1.11'
    install:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.10.2
    - go mod vendor
    - ls vendor
    script:
      ./bin/golangci-lint run

  - stage: build docker images
    install:
    - docker pull teamd2018/swagger-ui-geo-rest:latest
    script:
    - docker build -t swagger-ui-geo-rest -f Dockerfile.swagger-ui --cache-from teamd2018/swagger-ui-geo-rest:latest .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_NAME" --password-stdin
    - docker tag swagger-ui-geo-rest $DOCKERHUB_OWNER/swagger-ui-geo-rest
    - docker push $DOCKERHUB_OWNER/swagger-ui-geo-rest

  - stage: build docker images
    install:
    - docker pull teamd2018/geo-rest:latest
    script:
    - docker build -t geo-rest -f Dockerfile --cache-from teamd2018/geo-rest:latest .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_NAME" --password-stdin
    - docker tag geo-rest $DOCKERHUB_OWNER/geo-rest
    - docker push $DOCKERHUB_OWNER/geo-rest

  - stage: deploy
    language: bash
    services:
    - docker
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: develop
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_5cf62b557dad_key -iv $encrypted_5cf62b557dad_iv -in travis_key.enc -out travis_key -d

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

