jobs:
  include:
  - language: node.js
    nodejs:
    - '10.11'
    stage: test
    before_install:
    - npm install -g swagger-cli
    before_script:
    - cd api/
    script:
    - swagger-cli validate api.yaml
  - stage: deploy
    language: bash
    services:
    - docker
    install:
    - docker pull teamd2018/swagger-ui-geo-rest:latest
    - docker build -t swagger-ui-geo-rest -f Dockerfile.swagger-ui --cache-from teamd2018/swagger-ui-geo-rest:latest .
    - docker pull teamd2018/geo-rest:latest
    - docker build -t geo-rest -f Dockerfile --cache-from teamd2018/geo-rest:latest .
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: develop
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_5cf62b557dad_key -iv $encrypted_5cf62b557dad_iv -in travis_key.enc -out travis_key -d
