jobs:
  include:
  - stage: test
    name: "Unit Tests"
    language: go
    go:
    - '1.11'
    env:
    - GO111MODULE=on
    script: go test ./services ./controllers -v
    cache:
      directories:
      - $HOME/.cache/go-build
      - $GOPATH/pkg/mod
    if: (branch = develop) OR (branch = master)
    branches:
      only:
      - develop
      - master

  - stage: test
    name: "Integration Tests"
    language: go
    go:
    - '1.11'
    env:
    - GO111MODULE=on
    services:
    - docker
    script: go test -tags=elastic -run Integration ./services -v
    cache:
      directories:
      - $HOME/.cache/go-build
      - $GOPATH/pkg/mod
    if: (branch = develop) OR (branch = master)
    branches:
      only:
      - develop
      - master

  # - stage: test
  #   env:
  #   - GO111MODULE=on
  #   - GOFLAGS=-mod=vendor
  #   language: go
  #   go:
  #   - '1.11'
  #   install:
  #   - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.10.2
  #   - go mod vendor
  #   script:
  #     ./bin/golangci-lint run

  - stage: Build docker images
    name: "Geo rest"
    language: minimal
    services:
    - docker
    install:
    - docker pull teamd2018/geo-rest:latest
    script:
    - docker build -t $DOCKERHUB_OWNER/geo-rest:$TRAVIS_COMMIT -f Dockerfile --cache-from teamd2018/geo-rest:latest .
    - docker tag $DOCKERHUB_OWNER/geo-rest:$TRAVIS_COMMIT $DOCKERHUB_OWNER/geo-rest:latest
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_NAME" --password-stdin
    - docker push $DOCKERHUB_OWNER/geo-rest
    if: branch = master
    branches:
      only:
      - master

  - stage: deploy
    language: bash
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: develop
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_5cf62b557dad_key -iv $encrypted_5cf62b557dad_iv -in travis_key.enc -out travis_key -d
    if: branch = master
    branches:
      only:
      - master
