openapi: 3.0.0
info:
  version: "3.0.0-oas3"
  title: delivery-club-courier-monitor
  description: Delivery Club Courier Monitor
paths:
  /couriers:
    post:
      summary: Creates courier
      operationId: createCourier
      requestBody:
        description: Courier add to system
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Courier'
      responses:
        '201':
          description: Courier created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
        '400':
          description: Incorrect data for courier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Courier already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      parameters:
      - in: query
        name: lat
        schema:
          type: number
          format: float
      - in: query
        name: lon
        schema:
          type: number
          format: float
      - in: query
        name: address
        schema:
          type: string
      - in: query
        name: radius
        schema:
          type: number
          format: float
      - in: query
        name: viewport_down_lat
        schema:
          type: number
          format: float
      - in: query
        name: viewport_down_lon
        schema:
          type: number
          format: float
      - in: query
        name: viewport_up_lat
        schema:
          type: number
          format: float
      - in: query
        name: viewport_up_lon
        schema:
          type: number
          format: float
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Couriers'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  '/couriers/{courier_id}':
    get:
      description: Get complete courier description
      parameters:
      - $ref: '#/components/parameters/DeliveryClubId'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
        '404':
          description: Courier not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Error'
    put:
      parameters:
      - $ref: '#/components/parameters/DeliveryClubId'
      requestBody:
        description: Courier fields to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourierBase'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
        '404':
          description: Courier not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      parameters:
      - $ref: '#/components/parameters/DeliveryClubId'
      responses:
        '200':
          description: OK
        '404':
          description: Courier not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  '/couriers/{courier_id}/orders/{order_id}':
    post:
      parameters:
      - $ref: '#/components/parameters/OrderId'
      - $ref: '#/components/parameters/DeliveryClubId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      description: Update parameters of existing order
      parameters:
      - $ref: '#/components/parameters/OrderId'
      - $ref: '#/components/parameters/DeliveryClubId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderBase'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Transfer order to another courier
      parameters:
      - $ref: '#/components/parameters/OrderId'
      - $ref: '#/components/parameters/DeliveryClubId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      parameters:
      - $ref: '#/components/parameters/OrderId'
      - $ref: '#/components/parameters/DeliveryClubId'
      responses:
        '204':
          description: Ok
        '404':
          description: Courier not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/courier/{courier_id}/orders':
    get:
      parameters:
      - $ref: '#/components/parameters/DeliveryClubId'
      - name: since
        in: query
        schema:
          type: integer
          format: int64
      - name: asc
        in: query
        schema:
          type: boolean
          default: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orders'
        '404':
          description: Courier not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    DeliveryClubId:
      schema:
        type: integer
        format: int64
      in: path
      name: courier_id
      required: true
      description: Delivery Club courier id
    OrderId:
      schema:
        type: integer
        format: int64
      in: path
      name: order_id
      required: true
      description: Delivery Club order id
  schemas:
    CourierBase:
      properties:
        id:
          type: integer
          format: int64
          example: 42
        name:
          type: string
          example: Ахмед
        location:
          $ref: '#/components/schemas/Location'
        phone:
          description: Phone number in international format (without '+')
          type: string
          example: '79012345678'
        last_seen:
          description: Time in UTC format
          type: integer
          format: int64
          example: 1234567891
    Courier:
      allOf:
      - $ref: '#/components/schemas/CourierBase'
      required:
      - id
      - name
      - phone
    OrderBase:
      properties:
        id:
          type: integer
          format: int64
        courier_id:
          type: integer
          format: int64
        destination:
          $ref: '#/components/schemas/Location'
        soruce:
          $ref: '#/components/schemas/Location'
    Order:
      allOf:
      - $ref: '#/components/schemas/OrderBase'
      properties:
        courier:
          $ref: '#/components/schemas/Courier'
      required:
      - id
      - courier_id
      - destination
      - source
    Location:
      properties:
        lat:
          type: number
          format: float
          example: 55.79727
        lon:
          type: number
          format: float
          example: 37.537789
    Couriers:
      type: array
      items:
        $ref: '#/components/schemas/Courier'
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
          enum:
          - 9
          - 13
          - 15
          - 17
        message:
          type: string
      enum:
      - Courier already exists
      - Sorry, server error
      - One of parameters not found
      - One of parameter have incorrect format

servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/oleggator/delivery-club-courier-monitor/0.0.1