version: '3'
services:
  swagger-ui:
    image: dnnd/swagger-ui-geo-rest
    build: .
    ports:
    - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure