version: '3'
services:
  backend:
    image: teamd2018/geo-rest
    ports:
    - 8081:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    network:
    - geo-rest
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
    command: elasticsearch -Ehttp.port=9200 -Ehttp.cors.allow-origin="http://35.204.198.186:1358" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    network:
    - geo-rest
  tarantool:
    image: tarantool/tarantool:2
    ports:
    - 3301:3301
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    network:
    - geo-rest
networks:
  geo-rest:
