version: '3.5'
services:
  backend:
    image: teamd2018/geo-rest:new
    command: --config=/geo_rest_config.toml
    ports:
    - 8081:8080
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "./geo_rest_config.toml:/geo_rest_config.toml"
    networks:
    - geo-rest
    configs:
    - geo_rest_config.toml
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    command: elasticsearch -Ehttp.port=9200 -Ehttp.cors.allow-origin="http://dc.utkin.xyz:1358" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true
    ports:
    - 9200:9200
    - 9300:9300
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - geo-rest
    volumes:
    - esdata:/usr/share/elasticsearch/data
  tarantool:
    image: teamd2018/tarantool
    build: docker/tarantool
    ports:
      - 3301:3301
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - tarantool_data:/var/lib/tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=admin
    networks:
    - geo-rest

volumes:
  esdata:
    driver: local
  tarantool_data:
    driver: local

networks:
  geo-rest:
    name: geo-rest

configs:
  geo_rest_config.toml:
    external: true
