version: '3'
services:
  swagger-ui:
    image: teamd2018/swagger-ui-geo-rest
    ports:
    - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  geo-rest:
    image: teamd2018/geo-rest
    ports:
    - 8081:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
