/*
 * delivery-club-courier-monitor
 *
 * Delivery Club Courier Monitor
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CourierCourierIdOrdersGet - Get orders for courier
func CourierCourierIdOrdersGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdDelete - Delete courier from service
func CouriersCourierIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdGet - Get courier by id
func CouriersCourierIdGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdOrdersOrderIdDelete - Delete order
func CouriersCourierIdOrdersOrderIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdOrdersOrderIdPatch - Assign order to courier
func CouriersCourierIdOrdersOrderIdPatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdOrdersOrderIdPost - Create new order
func CouriersCourierIdOrdersOrderIdPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdOrdersOrderIdPut - Update existing order
func CouriersCourierIdOrdersOrderIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersCourierIdPut - Update existing courier
func CouriersCourierIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersGet - Get couriers in area
func CouriersGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CouriersPost - Creates courier
func CouriersPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
