/*
 * delivery-club-courier-monitor
 *
 * Delivery Club Courier Monitor
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Location - Geo-point (longitude, latitude)
type Location struct {

	// Latitude
	Lat float32 `json:"lat"`

	// Longitude
	Lon float32 `json:"lon"`
}
