/*
 * delivery-club-courier-monitor
 *
 * Delivery Club Courier Monitor
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Orders struct {
}
