/*
 * delivery-club-courier-monitor
 *
 * Delivery Club Courier Monitor
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case "GET":
			router.GET(route.Pattern, route.HandlerFunc)
		case "POST":
			router.POST(route.Pattern, route.HandlerFunc)
		case "PUT":
			router.PUT(route.Pattern, route.HandlerFunc)
		case "DELETE":
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"CourierCourierIdOrdersGet",
		http.MethodGet,
		"/courier/{courier_id}/orders",
		CourierCourierIdOrdersGet,
	},

	{
		"CouriersCourierIdDelete",
		http.MethodDelete,
		"/couriers/{courier_id}",
		CouriersCourierIdDelete,
	},

	{
		"CouriersCourierIdGet",
		http.MethodGet,
		"/couriers/{courier_id}",
		CouriersCourierIdGet,
	},

	{
		"CouriersCourierIdOrdersOrderIdDelete",
		http.MethodDelete,
		"/couriers/{courier_id}/orders/{order_id}",
		CouriersCourierIdOrdersOrderIdDelete,
	},

	{
		"CouriersCourierIdOrdersOrderIdPatch",
		http.MethodPatch,
		"/couriers/{courier_id}/orders/{order_id}",
		CouriersCourierIdOrdersOrderIdPatch,
	},

	{
		"CouriersCourierIdOrdersOrderIdPost",
		http.MethodPost,
		"/couriers/{courier_id}/orders/{order_id}",
		CouriersCourierIdOrdersOrderIdPost,
	},

	{
		"CouriersCourierIdOrdersOrderIdPut",
		http.MethodPut,
		"/couriers/{courier_id}/orders/{order_id}",
		CouriersCourierIdOrdersOrderIdPut,
	},

	{
		"CouriersCourierIdPut",
		http.MethodPut,
		"/couriers/{courier_id}",
		CouriersCourierIdPut,
	},

	{
		"CouriersGet",
		http.MethodGet,
		"/couriers",
		CouriersGet,
	},

	{
		"CouriersPost",
		http.MethodPost,
		"/couriers",
		CouriersPost,
	},
}
