openapi: 3.0.0
info:
  version: "0.0.1"
  title: delivery-club-courier-monitor
  description: Delivery Club Courier Monitor
paths:
  /couriers:
    $ref: 'couriers.yml'
  '/couriers/{courier_id}':
    $ref: 'courier_id.yml'
  '/couriers/{courier_id}/orders/{order_id}':
    $ref: 'courier_order.yml'
  '/courier/{courier_id}/orders':
    $ref: 'courier_orders.yml'

components:
  parameters:
    DeliveryClubID:
      $ref: 'parameters.yml#/DeliveryClubID'
    OrderID:
      $ref: 'parameters.yml#/OrderID'
  schemas:
    CourierBase:
      $ref: 'schemas.yml#/CourierBase'
    Courier:
      $ref: 'schemas.yml#/Courier'
    OrderBase:
      $ref: 'schemas.yml#/OrderBase'
    Order:
      $ref: 'schemas.yml#/Order'
    Location:
      $ref: 'schemas.yml#/Location'
    Couriers:
      $ref: 'schemas.yml#/Couriers'
    Orders:
      $ref: 'schemas.yml#/Orders'
    Error:
      $ref: 'schemas.yml#/Error'

servers:
- description: SwaggerHub API Auto Mocking
  url: http://dc.utkin.xyz:8081
