DeliveryClubID:
  schema:
    type: integer
    format: int64
  in: path
  name: courier_id
  required: true
  description: Delivery Club courier id

OrderID:
  schema:
    type: integer
    format: int64
  in: path
  name: order_id
  required: true
  description: Delivery Club order id

GeoFilter:
  in: query
  style: form
  explode: true
  description: Search area
  name: filter
  schema:
    type: object
    oneOf:
    - $ref: 'schemas.yml#/Circle'
    - $ref: 'schemas.yml#/Box'
    - $ref: 'schemas.yml#/Zone'